apiVersion: apps/v1
kind: Deployment
metadata:
  name: lgr-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lgr-api
  template:
    metadata:
      labels:
        app: lgr-api
    spec:
      containers:
      - name: lgr-api
        image: rs401/letsgoripapi:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        ports:
          - containerPort: 9000
        env:
          - name: API_PORT
            valueFrom:
              configMapKeyRef:
                name: lgr-api-config
                key: api_port
          - name: AUTHSVC_HOST
            valueFrom:
              configMapKeyRef:
                name: lgr-api-config
                key: authsvc_host
          - name: AUTHSVC_PORT
            valueFrom:
              configMapKeyRef:
                name: lgr-api-config
                key: authsvc_port
          - name: FORUMSVC_HOST
            valueFrom:
              configMapKeyRef:
                name: lgr-api-config
                key: forumsvc_host
          - name: FORUMSVC_PORT
            valueFrom:
              configMapKeyRef:
                name: lgr-api-config
                key: forumsvc_port
          - name: PLACESVC_HOST
            valueFrom:
              configMapKeyRef:
                name: lgr-api-config
                key: placesvc_host
          - name: PLACESVC_PORT
            valueFrom:
              configMapKeyRef:
                name: lgr-api-config
                key: placesvc_port
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: lgr-api-secrets
                key: jwt_secret
          - name: REFRESH_SECRET
            valueFrom:
              secretKeyRef:
                name: lgr-api-secrets
                key: refresh_secret