apiVersion: apps/v1
kind: Deployment
metadata:
  name: lgr-authsvc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lgr-authsvc
  template:
    metadata:
      labels:
        app: lgr-authsvc
    spec:
      containers:
      - name: lgr-authsvc
        image: rs401/letsgoripauthsvc:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        ports:
          - containerPort: 9001
        env:
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: lgr-authsvc-config
                key: db_user
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: pg-secrets
                key: db_pass
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: lgr-authsvc-config
                key: db_host
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: lgr-authsvc-config
                key: db_name
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: lgr-authsvc-config
                key: db_port
          - name: AUTHSVC_PORT
            valueFrom:
              configMapKeyRef:
                name: lgr-authsvc-config
                key: authsvc_port