// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: place.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Place struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId    uint64  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StateId   uint64  `protobuf:"varint,3,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	Name      float64 `protobuf:"fixed64,4,opt,name=name,proto3" json:"name,omitempty"`
	Latitude  float64 `protobuf:"fixed64,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *Place) Reset() {
	*x = Place{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Place) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Place) ProtoMessage() {}

func (x *Place) ProtoReflect() protoreflect.Message {
	mi := &file_place_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Place.ProtoReflect.Descriptor instead.
func (*Place) Descriptor() ([]byte, []int) {
	return file_place_proto_rawDescGZIP(), []int{0}
}

func (x *Place) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Place) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Place) GetStateId() uint64 {
	if x != nil {
		return x.StateId
	}
	return 0
}

func (x *Place) GetName() float64 {
	if x != nil {
		return x.Name
	}
	return 0
}

func (x *Place) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Place) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type PlaceIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PlaceIdRequest) Reset() {
	*x = PlaceIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaceIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceIdRequest) ProtoMessage() {}

func (x *PlaceIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_place_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceIdRequest.ProtoReflect.Descriptor instead.
func (*PlaceIdRequest) Descriptor() ([]byte, []int) {
	return file_place_proto_rawDescGZIP(), []int{1}
}

func (x *PlaceIdRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PlaceIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PlaceIdResponse) Reset() {
	*x = PlaceIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaceIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceIdResponse) ProtoMessage() {}

func (x *PlaceIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_place_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceIdResponse.ProtoReflect.Descriptor instead.
func (*PlaceIdResponse) Descriptor() ([]byte, []int) {
	return file_place_proto_rawDescGZIP(), []int{2}
}

func (x *PlaceIdResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPlacesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateId uint64 `protobuf:"varint,1,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
}

func (x *GetPlacesRequest) Reset() {
	*x = GetPlacesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlacesRequest) ProtoMessage() {}

func (x *GetPlacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_place_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlacesRequest.ProtoReflect.Descriptor instead.
func (*GetPlacesRequest) Descriptor() ([]byte, []int) {
	return file_place_proto_rawDescGZIP(), []int{3}
}

func (x *GetPlacesRequest) GetStateId() uint64 {
	if x != nil {
		return x.StateId
	}
	return 0
}

var File_place_proto protoreflect.FileDescriptor

var file_place_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70,
	0x62, 0x22, 0x99, 0x01, 0x0a, 0x05, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x73, 0x74, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x20, 0x0a,
	0x0e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x21, 0x0a, 0x0f, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x2d, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x73, 0x74, 0x61, 0x74, 0x65, 0x49,
	0x64, 0x32, 0x89, 0x02, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x2d, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x63,
	0x65, 0x12, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x1a, 0x13, 0x2e, 0x70,
	0x62, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x33, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x12, 0x2e,
	0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x49, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61,
	0x63, 0x65, 0x73, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x63,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x50,
	0x6c, 0x61, 0x63, 0x65, 0x30, 0x01, 0x12, 0x2d, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x50, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65,
	0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50,
	0x6c, 0x61, 0x63, 0x65, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c,
	0x61, 0x63, 0x65, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1f, 0x5a,
	0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x73, 0x34, 0x30,
	0x31, 0x2f, 0x6c, 0x65, 0x74, 0x73, 0x67, 0x6f, 0x72, 0x69, 0x70, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_place_proto_rawDescOnce sync.Once
	file_place_proto_rawDescData = file_place_proto_rawDesc
)

func file_place_proto_rawDescGZIP() []byte {
	file_place_proto_rawDescOnce.Do(func() {
		file_place_proto_rawDescData = protoimpl.X.CompressGZIP(file_place_proto_rawDescData)
	})
	return file_place_proto_rawDescData
}

var file_place_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_place_proto_goTypes = []interface{}{
	(*Place)(nil),            // 0: pb.Place
	(*PlaceIdRequest)(nil),   // 1: pb.PlaceIdRequest
	(*PlaceIdResponse)(nil),  // 2: pb.PlaceIdResponse
	(*GetPlacesRequest)(nil), // 3: pb.GetPlacesRequest
}
var file_place_proto_depIdxs = []int32{
	0, // 0: pb.PlaceService.CreatePlace:input_type -> pb.Place
	1, // 1: pb.PlaceService.GetPlace:input_type -> pb.PlaceIdRequest
	3, // 2: pb.PlaceService.GetPlaces:input_type -> pb.GetPlacesRequest
	0, // 3: pb.PlaceService.UpdatePlace:input_type -> pb.Place
	1, // 4: pb.PlaceService.DeletePlace:input_type -> pb.PlaceIdRequest
	2, // 5: pb.PlaceService.CreatePlace:output_type -> pb.PlaceIdResponse
	2, // 6: pb.PlaceService.GetPlace:output_type -> pb.PlaceIdResponse
	0, // 7: pb.PlaceService.GetPlaces:output_type -> pb.Place
	2, // 8: pb.PlaceService.UpdatePlace:output_type -> pb.PlaceIdResponse
	2, // 9: pb.PlaceService.DeletePlace:output_type -> pb.PlaceIdResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_place_proto_init() }
func file_place_proto_init() {
	if File_place_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_place_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Place); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaceIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaceIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlacesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_place_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_place_proto_goTypes,
		DependencyIndexes: file_place_proto_depIdxs,
		MessageInfos:      file_place_proto_msgTypes,
	}.Build()
	File_place_proto = out.File
	file_place_proto_rawDesc = nil
	file_place_proto_goTypes = nil
	file_place_proto_depIdxs = nil
}
